# Generated by Django 2.2 on 2020-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200202_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='top_category',
            field=models.ForeignKey(default=1, on_delete=None, to='content.Category'),
            preserve_default=False,
        ),
    ]
