# Generated by Django 2.2 on 2020-02-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200202_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='top_category',
            field=models.ForeignKey(null=True, on_delete=None, to='content.Category'),
        ),
    ]
