# Generated by Django 2.2 on 2020-02-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200202_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='top_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='content.Category'),
        ),
    ]
